[package]
name = "rust_counter"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.101"
wasm-bindgen-futures = "0.4.51"
js-sys = "0.3"
once_cell = "1.21.3"
web-sys = { version = "0.3", features = ["console"] }
console_error_panic_hook = "0.1.6"

[lib]
crate-type = ["cdylib"]
